parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]\n>"
alias vli="vault login --method oidc"
alias vim="nvim"
alias uu="sudo apt update && sudo apt upgrade -y"
alias tf="terraform"
alias tfa="terraform apply"
alias tfws="terraform workspace"
alias tfadev="terraform workspace select -or-create dev && terraform apply --var-file dev.tfvars"
alias tfaqa="terraform workspace select -or-create qa && terraform apply --var-file qa.tfvars"
alias tfaprod="terraform workspace select -or-create prod && terraform apply --var-file prod.tfvars"
alias python="python3"
alias ls="lsd -al"
alias work="cd ~/Dev/24g/"
alias pers="cd ~/Dev/Personal/"
alias bashrc="vim ~/.bashrc"
alias python="python3"
alias ls="lsd -al"
alias work="cd ~/Dev/24g/"
alias pers="cd ~/Dev/Personal/"
alias bashrc="vim ~/.bashrc"
alias python="python3"
alias ls="lsd -al"
alias work="cd ~/Dev/24g/"
alias pers="cd ~/Dev/Personal/"
alias bashrc="vim ~/.bashrc"
alias basha="vim ~/.bash_aliases"
alias vimrc="vim ~/.config/nvim"
alias creds="vim ~/.aws/credentials"
alias tfTemp="cp -r ~/Dev/24g/24g-architecture/examples/terraform/projects/clutch/ ~/Dev/24g/24g-architecture/aws/experiential-24g/vpc/experiential-vpc/"
alias tfTempFE="cp -r ~/Dev/24g/24g-architecture/examples/terraform/projects/clutch-fe-only/ ~/Dev/24g/24g-architecture/aws/experiential-24g/vpc/experiential-vpc/"
alias socketio-client="node ~/Dev/scripts/socketio-test.js"
alias updates=". ~/Dev/scripts/update/update.sh"
